set(_CATKIN_CURRENT_PACKAGE "nav_planner")
set(nav_planner_VERSION "0.0.0")
set(nav_planner_MAINTAINER "kalana <kalana@todo.todo>")
set(nav_planner_PACKAGE_FORMAT "2")
set(nav_planner_BUILD_DEPENDS "roscpp" "rospy" "message_generation")
set(nav_planner_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(nav_planner_BUILDTOOL_DEPENDS "catkin")
set(nav_planner_BUILDTOOL_EXPORT_DEPENDS )
set(nav_planner_EXEC_DEPENDS "roscpp" "rospy" "message_runtime")
set(nav_planner_RUN_DEPENDS "roscpp" "rospy" "message_runtime")
set(nav_planner_TEST_DEPENDS )
set(nav_planner_DOC_DEPENDS )
set(nav_planner_URL_WEBSITE "")
set(nav_planner_URL_BUGTRACKER "")
set(nav_planner_URL_REPOSITORY "")
set(nav_planner_DEPRECATED "")