(cl:defpackage nav_planner-srv
  (:use )
  (:export
   "BASEDRIVE"
   "<BASEDRIVE-REQUEST>"
   "BASEDRIVE-REQUEST"
   "<BASEDRIVE-RESPONSE>"
   "BASEDRIVE-RESPONSE"
   "GOALCONTROL"
   "<GOALCONTROL-REQUEST>"
   "GOALCONTROL-REQUEST"
   "<GOALCONTROL-RESPONSE>"
   "GOALCONTROL-RESPONSE"
   "WATERDETECT"
   "<WATERDETECT-REQUEST>"
   "WATERDETECT-REQUEST"
   "<WATERDETECT-RESPONSE>"
   "WATERDETECT-RESPONSE"
  ))

