// Generated by gencpp from file nav_planner/baseRotate.msg
// DO NOT EDIT!


#ifndef NAV_PLANNER_MESSAGE_BASEROTATE_H
#define NAV_PLANNER_MESSAGE_BASEROTATE_H

#include <ros/service_traits.h>


#include <nav_planner/baseRotateRequest.h>
#include <nav_planner/baseRotateResponse.h>


namespace nav_planner
{

struct baseRotate
{

typedef baseRotateRequest Request;
typedef baseRotateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct baseRotate
} // namespace nav_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nav_planner::baseRotate > {
  static const char* value()
  {
    return "a933da1aed447ccd941e96046fc95d53";
  }

  static const char* value(const ::nav_planner::baseRotate&) { return value(); }
};

template<>
struct DataType< ::nav_planner::baseRotate > {
  static const char* value()
  {
    return "nav_planner/baseRotate";
  }

  static const char* value(const ::nav_planner::baseRotate&) { return value(); }
};


// service_traits::MD5Sum< ::nav_planner::baseRotateRequest> should match 
// service_traits::MD5Sum< ::nav_planner::baseRotate > 
template<>
struct MD5Sum< ::nav_planner::baseRotateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nav_planner::baseRotate >::value();
  }
  static const char* value(const ::nav_planner::baseRotateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_planner::baseRotateRequest> should match 
// service_traits::DataType< ::nav_planner::baseRotate > 
template<>
struct DataType< ::nav_planner::baseRotateRequest>
{
  static const char* value()
  {
    return DataType< ::nav_planner::baseRotate >::value();
  }
  static const char* value(const ::nav_planner::baseRotateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nav_planner::baseRotateResponse> should match 
// service_traits::MD5Sum< ::nav_planner::baseRotate > 
template<>
struct MD5Sum< ::nav_planner::baseRotateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nav_planner::baseRotate >::value();
  }
  static const char* value(const ::nav_planner::baseRotateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_planner::baseRotateResponse> should match 
// service_traits::DataType< ::nav_planner::baseRotate > 
template<>
struct DataType< ::nav_planner::baseRotateResponse>
{
  static const char* value()
  {
    return DataType< ::nav_planner::baseRotate >::value();
  }
  static const char* value(const ::nav_planner::baseRotateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAV_PLANNER_MESSAGE_BASEROTATE_H
