// Generated by gencpp from file nav_planner/baseRotateRequest.msg
// DO NOT EDIT!


#ifndef NAV_PLANNER_MESSAGE_BASEROTATEREQUEST_H
#define NAV_PLANNER_MESSAGE_BASEROTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nav_planner
{
template <class ContainerAllocator>
struct baseRotateRequest_
{
  typedef baseRotateRequest_<ContainerAllocator> Type;

  baseRotateRequest_()
    : execute(false)  {
    }
  baseRotateRequest_(const ContainerAllocator& _alloc)
    : execute(false)  {
  (void)_alloc;
    }



   typedef uint8_t _execute_type;
  _execute_type execute;





  typedef boost::shared_ptr< ::nav_planner::baseRotateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nav_planner::baseRotateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct baseRotateRequest_

typedef ::nav_planner::baseRotateRequest_<std::allocator<void> > baseRotateRequest;

typedef boost::shared_ptr< ::nav_planner::baseRotateRequest > baseRotateRequestPtr;
typedef boost::shared_ptr< ::nav_planner::baseRotateRequest const> baseRotateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nav_planner::baseRotateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nav_planner::baseRotateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nav_planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'nav_planner': ['/home/kalana/FYP/src/nav_planner/msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nav_planner::baseRotateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_planner::baseRotateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_planner::baseRotateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_planner::baseRotateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_planner::baseRotateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_planner::baseRotateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nav_planner::baseRotateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "371e747b927788fd0b8812d474ff9a56";
  }

  static const char* value(const ::nav_planner::baseRotateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x371e747b927788fdULL;
  static const uint64_t static_value2 = 0x0b8812d474ff9a56ULL;
};

template<class ContainerAllocator>
struct DataType< ::nav_planner::baseRotateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_planner/baseRotateRequest";
  }

  static const char* value(const ::nav_planner::baseRotateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nav_planner::baseRotateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool execute\n\
";
  }

  static const char* value(const ::nav_planner::baseRotateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nav_planner::baseRotateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.execute);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct baseRotateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nav_planner::baseRotateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nav_planner::baseRotateRequest_<ContainerAllocator>& v)
  {
    s << indent << "execute: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.execute);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAV_PLANNER_MESSAGE_BASEROTATEREQUEST_H
