// Generated by gencpp from file nav_planner/goalControl.msg
// DO NOT EDIT!


#ifndef NAV_PLANNER_MESSAGE_GOALCONTROL_H
#define NAV_PLANNER_MESSAGE_GOALCONTROL_H

#include <ros/service_traits.h>


#include <nav_planner/goalControlRequest.h>
#include <nav_planner/goalControlResponse.h>


namespace nav_planner
{

struct goalControl
{

typedef goalControlRequest Request;
typedef goalControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct goalControl
} // namespace nav_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nav_planner::goalControl > {
  static const char* value()
  {
    return "4264199fe659d58fcdd2ad61fb4fcaec";
  }

  static const char* value(const ::nav_planner::goalControl&) { return value(); }
};

template<>
struct DataType< ::nav_planner::goalControl > {
  static const char* value()
  {
    return "nav_planner/goalControl";
  }

  static const char* value(const ::nav_planner::goalControl&) { return value(); }
};


// service_traits::MD5Sum< ::nav_planner::goalControlRequest> should match 
// service_traits::MD5Sum< ::nav_planner::goalControl > 
template<>
struct MD5Sum< ::nav_planner::goalControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nav_planner::goalControl >::value();
  }
  static const char* value(const ::nav_planner::goalControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_planner::goalControlRequest> should match 
// service_traits::DataType< ::nav_planner::goalControl > 
template<>
struct DataType< ::nav_planner::goalControlRequest>
{
  static const char* value()
  {
    return DataType< ::nav_planner::goalControl >::value();
  }
  static const char* value(const ::nav_planner::goalControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nav_planner::goalControlResponse> should match 
// service_traits::MD5Sum< ::nav_planner::goalControl > 
template<>
struct MD5Sum< ::nav_planner::goalControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nav_planner::goalControl >::value();
  }
  static const char* value(const ::nav_planner::goalControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_planner::goalControlResponse> should match 
// service_traits::DataType< ::nav_planner::goalControl > 
template<>
struct DataType< ::nav_planner::goalControlResponse>
{
  static const char* value()
  {
    return DataType< ::nav_planner::goalControl >::value();
  }
  static const char* value(const ::nav_planner::goalControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAV_PLANNER_MESSAGE_GOALCONTROL_H
