// Generated by gencpp from file nav_planner/goalRemove.msg
// DO NOT EDIT!


#ifndef NAV_PLANNER_MESSAGE_GOALREMOVE_H
#define NAV_PLANNER_MESSAGE_GOALREMOVE_H

#include <ros/service_traits.h>


#include <nav_planner/goalRemoveRequest.h>
#include <nav_planner/goalRemoveResponse.h>


namespace nav_planner
{

struct goalRemove
{

typedef goalRemoveRequest Request;
typedef goalRemoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct goalRemove
} // namespace nav_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nav_planner::goalRemove > {
  static const char* value()
  {
    return "58d59f258ca9f2d2ba375d9428a7f1de";
  }

  static const char* value(const ::nav_planner::goalRemove&) { return value(); }
};

template<>
struct DataType< ::nav_planner::goalRemove > {
  static const char* value()
  {
    return "nav_planner/goalRemove";
  }

  static const char* value(const ::nav_planner::goalRemove&) { return value(); }
};


// service_traits::MD5Sum< ::nav_planner::goalRemoveRequest> should match 
// service_traits::MD5Sum< ::nav_planner::goalRemove > 
template<>
struct MD5Sum< ::nav_planner::goalRemoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nav_planner::goalRemove >::value();
  }
  static const char* value(const ::nav_planner::goalRemoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_planner::goalRemoveRequest> should match 
// service_traits::DataType< ::nav_planner::goalRemove > 
template<>
struct DataType< ::nav_planner::goalRemoveRequest>
{
  static const char* value()
  {
    return DataType< ::nav_planner::goalRemove >::value();
  }
  static const char* value(const ::nav_planner::goalRemoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nav_planner::goalRemoveResponse> should match 
// service_traits::MD5Sum< ::nav_planner::goalRemove > 
template<>
struct MD5Sum< ::nav_planner::goalRemoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nav_planner::goalRemove >::value();
  }
  static const char* value(const ::nav_planner::goalRemoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_planner::goalRemoveResponse> should match 
// service_traits::DataType< ::nav_planner::goalRemove > 
template<>
struct DataType< ::nav_planner::goalRemoveResponse>
{
  static const char* value()
  {
    return DataType< ::nav_planner::goalRemove >::value();
  }
  static const char* value(const ::nav_planner::goalRemoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAV_PLANNER_MESSAGE_GOALREMOVE_H
