// Generated by gencpp from file nav_planner/goalControlResponse.msg
// DO NOT EDIT!


#ifndef NAV_PLANNER_MESSAGE_GOALCONTROLRESPONSE_H
#define NAV_PLANNER_MESSAGE_GOALCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nav_planner
{
template <class ContainerAllocator>
struct goalControlResponse_
{
  typedef goalControlResponse_<ContainerAllocator> Type;

  goalControlResponse_()
    : isNull(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  goalControlResponse_(const ContainerAllocator& _alloc)
    : isNull(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _isNull_type;
  _isNull_type isNull;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::nav_planner::goalControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nav_planner::goalControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct goalControlResponse_

typedef ::nav_planner::goalControlResponse_<std::allocator<void> > goalControlResponse;

typedef boost::shared_ptr< ::nav_planner::goalControlResponse > goalControlResponsePtr;
typedef boost::shared_ptr< ::nav_planner::goalControlResponse const> goalControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nav_planner::goalControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nav_planner::goalControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nav_planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'nav_planner': ['/home/kalana/FYP/src/nav_planner/msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nav_planner::goalControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_planner::goalControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_planner::goalControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_planner::goalControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_planner::goalControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_planner::goalControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nav_planner::goalControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4dba3313c0977b613eb2d8aab1137f2d";
  }

  static const char* value(const ::nav_planner::goalControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4dba3313c0977b61ULL;
  static const uint64_t static_value2 = 0x3eb2d8aab1137f2dULL;
};

template<class ContainerAllocator>
struct DataType< ::nav_planner::goalControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_planner/goalControlResponse";
  }

  static const char* value(const ::nav_planner::goalControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nav_planner::goalControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isNull\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
";
  }

  static const char* value(const ::nav_planner::goalControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nav_planner::goalControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isNull);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goalControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nav_planner::goalControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nav_planner::goalControlResponse_<ContainerAllocator>& v)
  {
    s << indent << "isNull: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isNull);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAV_PLANNER_MESSAGE_GOALCONTROLRESPONSE_H
