// Generated by gencpp from file nav_planner/gridMap.msg
// DO NOT EDIT!


#ifndef NAV_PLANNER_MESSAGE_GRIDMAP_H
#define NAV_PLANNER_MESSAGE_GRIDMAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_planner/gridRow.h>
#include <nav_planner/pointData.h>

namespace nav_planner
{
template <class ContainerAllocator>
struct gridMap_
{
  typedef gridMap_<ContainerAllocator> Type;

  gridMap_()
    : grid()
    , path()
    , pathLength(0)  {
    }
  gridMap_(const ContainerAllocator& _alloc)
    : grid(_alloc)
    , path(_alloc)
    , pathLength(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::nav_planner::gridRow_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nav_planner::gridRow_<ContainerAllocator> >::other >  _grid_type;
  _grid_type grid;

   typedef std::vector< ::nav_planner::pointData_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nav_planner::pointData_<ContainerAllocator> >::other >  _path_type;
  _path_type path;

   typedef int16_t _pathLength_type;
  _pathLength_type pathLength;





  typedef boost::shared_ptr< ::nav_planner::gridMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nav_planner::gridMap_<ContainerAllocator> const> ConstPtr;

}; // struct gridMap_

typedef ::nav_planner::gridMap_<std::allocator<void> > gridMap;

typedef boost::shared_ptr< ::nav_planner::gridMap > gridMapPtr;
typedef boost::shared_ptr< ::nav_planner::gridMap const> gridMapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nav_planner::gridMap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nav_planner::gridMap_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nav_planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'nav_planner': ['/home/kalana/FYP/src/nav_planner/msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nav_planner::gridMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_planner::gridMap_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_planner::gridMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_planner::gridMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_planner::gridMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_planner::gridMap_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nav_planner::gridMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7283370e017ac387872171d01ea443ab";
  }

  static const char* value(const ::nav_planner::gridMap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7283370e017ac387ULL;
  static const uint64_t static_value2 = 0x872171d01ea443abULL;
};

template<class ContainerAllocator>
struct DataType< ::nav_planner::gridMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_planner/gridMap";
  }

  static const char* value(const ::nav_planner::gridMap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nav_planner::gridMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gridRow[] grid\n\
pointData[] path\n\
int16 pathLength\n\
================================================================================\n\
MSG: nav_planner/gridRow\n\
gridPoint[] row\n\
\n\
================================================================================\n\
MSG: nav_planner/gridPoint\n\
int8 init\n\
int8 proc\n\
================================================================================\n\
MSG: nav_planner/pointData\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::nav_planner::gridMap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nav_planner::gridMap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grid);
      stream.next(m.path);
      stream.next(m.pathLength);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gridMap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nav_planner::gridMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nav_planner::gridMap_<ContainerAllocator>& v)
  {
    s << indent << "grid[]" << std::endl;
    for (size_t i = 0; i < v.grid.size(); ++i)
    {
      s << indent << "  grid[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nav_planner::gridRow_<ContainerAllocator> >::stream(s, indent + "    ", v.grid[i]);
    }
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nav_planner::pointData_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
    s << indent << "pathLength: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pathLength);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAV_PLANNER_MESSAGE_GRIDMAP_H
