// Generated by gencpp from file nav_planner/mapControlRequest.msg
// DO NOT EDIT!


#ifndef NAV_PLANNER_MESSAGE_MAPCONTROLREQUEST_H
#define NAV_PLANNER_MESSAGE_MAPCONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nav_planner
{
template <class ContainerAllocator>
struct mapControlRequest_
{
  typedef mapControlRequest_<ContainerAllocator> Type;

  mapControlRequest_()
    : requestTree(false)  {
    }
  mapControlRequest_(const ContainerAllocator& _alloc)
    : requestTree(false)  {
  (void)_alloc;
    }



   typedef uint8_t _requestTree_type;
  _requestTree_type requestTree;





  typedef boost::shared_ptr< ::nav_planner::mapControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nav_planner::mapControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct mapControlRequest_

typedef ::nav_planner::mapControlRequest_<std::allocator<void> > mapControlRequest;

typedef boost::shared_ptr< ::nav_planner::mapControlRequest > mapControlRequestPtr;
typedef boost::shared_ptr< ::nav_planner::mapControlRequest const> mapControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nav_planner::mapControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nav_planner::mapControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nav_planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'nav_planner': ['/home/kalana/FYP/src/nav_planner/msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nav_planner::mapControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nav_planner::mapControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_planner::mapControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nav_planner::mapControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_planner::mapControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nav_planner::mapControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nav_planner::mapControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c17e1270e073c6ebb2aca9096a5fb9e1";
  }

  static const char* value(const ::nav_planner::mapControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc17e1270e073c6ebULL;
  static const uint64_t static_value2 = 0xb2aca9096a5fb9e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::nav_planner::mapControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_planner/mapControlRequest";
  }

  static const char* value(const ::nav_planner::mapControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nav_planner::mapControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool requestTree\n\
";
  }

  static const char* value(const ::nav_planner::mapControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nav_planner::mapControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.requestTree);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mapControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nav_planner::mapControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nav_planner::mapControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "requestTree: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.requestTree);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAV_PLANNER_MESSAGE_MAPCONTROLREQUEST_H
