// Generated by gencpp from file nav_planner/mapControl.msg
// DO NOT EDIT!


#ifndef NAV_PLANNER_MESSAGE_MAPCONTROL_H
#define NAV_PLANNER_MESSAGE_MAPCONTROL_H

#include <ros/service_traits.h>


#include <nav_planner/mapControlRequest.h>
#include <nav_planner/mapControlResponse.h>


namespace nav_planner
{

struct mapControl
{

typedef mapControlRequest Request;
typedef mapControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mapControl
} // namespace nav_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nav_planner::mapControl > {
  static const char* value()
  {
    return "a2ef632b8b905476992515bef0f3da16";
  }

  static const char* value(const ::nav_planner::mapControl&) { return value(); }
};

template<>
struct DataType< ::nav_planner::mapControl > {
  static const char* value()
  {
    return "nav_planner/mapControl";
  }

  static const char* value(const ::nav_planner::mapControl&) { return value(); }
};


// service_traits::MD5Sum< ::nav_planner::mapControlRequest> should match 
// service_traits::MD5Sum< ::nav_planner::mapControl > 
template<>
struct MD5Sum< ::nav_planner::mapControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nav_planner::mapControl >::value();
  }
  static const char* value(const ::nav_planner::mapControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_planner::mapControlRequest> should match 
// service_traits::DataType< ::nav_planner::mapControl > 
template<>
struct DataType< ::nav_planner::mapControlRequest>
{
  static const char* value()
  {
    return DataType< ::nav_planner::mapControl >::value();
  }
  static const char* value(const ::nav_planner::mapControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nav_planner::mapControlResponse> should match 
// service_traits::MD5Sum< ::nav_planner::mapControl > 
template<>
struct MD5Sum< ::nav_planner::mapControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nav_planner::mapControl >::value();
  }
  static const char* value(const ::nav_planner::mapControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_planner::mapControlResponse> should match 
// service_traits::DataType< ::nav_planner::mapControl > 
template<>
struct DataType< ::nav_planner::mapControlResponse>
{
  static const char* value()
  {
    return DataType< ::nav_planner::mapControl >::value();
  }
  static const char* value(const ::nav_planner::mapControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAV_PLANNER_MESSAGE_MAPCONTROL_H
