// Generated by gencpp from file nav_planner/mapSave.msg
// DO NOT EDIT!


#ifndef NAV_PLANNER_MESSAGE_MAPSAVE_H
#define NAV_PLANNER_MESSAGE_MAPSAVE_H

#include <ros/service_traits.h>


#include <nav_planner/mapSaveRequest.h>
#include <nav_planner/mapSaveResponse.h>


namespace nav_planner
{

struct mapSave
{

typedef mapSaveRequest Request;
typedef mapSaveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mapSave
} // namespace nav_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nav_planner::mapSave > {
  static const char* value()
  {
    return "f6ec99713685605bc49d86e471c42eb7";
  }

  static const char* value(const ::nav_planner::mapSave&) { return value(); }
};

template<>
struct DataType< ::nav_planner::mapSave > {
  static const char* value()
  {
    return "nav_planner/mapSave";
  }

  static const char* value(const ::nav_planner::mapSave&) { return value(); }
};


// service_traits::MD5Sum< ::nav_planner::mapSaveRequest> should match 
// service_traits::MD5Sum< ::nav_planner::mapSave > 
template<>
struct MD5Sum< ::nav_planner::mapSaveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nav_planner::mapSave >::value();
  }
  static const char* value(const ::nav_planner::mapSaveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_planner::mapSaveRequest> should match 
// service_traits::DataType< ::nav_planner::mapSave > 
template<>
struct DataType< ::nav_planner::mapSaveRequest>
{
  static const char* value()
  {
    return DataType< ::nav_planner::mapSave >::value();
  }
  static const char* value(const ::nav_planner::mapSaveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nav_planner::mapSaveResponse> should match 
// service_traits::MD5Sum< ::nav_planner::mapSave > 
template<>
struct MD5Sum< ::nav_planner::mapSaveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nav_planner::mapSave >::value();
  }
  static const char* value(const ::nav_planner::mapSaveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_planner::mapSaveResponse> should match 
// service_traits::DataType< ::nav_planner::mapSave > 
template<>
struct DataType< ::nav_planner::mapSaveResponse>
{
  static const char* value()
  {
    return DataType< ::nav_planner::mapSave >::value();
  }
  static const char* value(const ::nav_planner::mapSaveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAV_PLANNER_MESSAGE_MAPSAVE_H
