// Generated by gencpp from file nav_planner/systemControl.msg
// DO NOT EDIT!


#ifndef NAV_PLANNER_MESSAGE_SYSTEMCONTROL_H
#define NAV_PLANNER_MESSAGE_SYSTEMCONTROL_H

#include <ros/service_traits.h>


#include <nav_planner/systemControlRequest.h>
#include <nav_planner/systemControlResponse.h>


namespace nav_planner
{

struct systemControl
{

typedef systemControlRequest Request;
typedef systemControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct systemControl
} // namespace nav_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nav_planner::systemControl > {
  static const char* value()
  {
    return "28dadd83d564c0f1c7317577c2a315b5";
  }

  static const char* value(const ::nav_planner::systemControl&) { return value(); }
};

template<>
struct DataType< ::nav_planner::systemControl > {
  static const char* value()
  {
    return "nav_planner/systemControl";
  }

  static const char* value(const ::nav_planner::systemControl&) { return value(); }
};


// service_traits::MD5Sum< ::nav_planner::systemControlRequest> should match 
// service_traits::MD5Sum< ::nav_planner::systemControl > 
template<>
struct MD5Sum< ::nav_planner::systemControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nav_planner::systemControl >::value();
  }
  static const char* value(const ::nav_planner::systemControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_planner::systemControlRequest> should match 
// service_traits::DataType< ::nav_planner::systemControl > 
template<>
struct DataType< ::nav_planner::systemControlRequest>
{
  static const char* value()
  {
    return DataType< ::nav_planner::systemControl >::value();
  }
  static const char* value(const ::nav_planner::systemControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nav_planner::systemControlResponse> should match 
// service_traits::MD5Sum< ::nav_planner::systemControl > 
template<>
struct MD5Sum< ::nav_planner::systemControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nav_planner::systemControl >::value();
  }
  static const char* value(const ::nav_planner::systemControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nav_planner::systemControlResponse> should match 
// service_traits::DataType< ::nav_planner::systemControl > 
template<>
struct DataType< ::nav_planner::systemControlResponse>
{
  static const char* value()
  {
    return DataType< ::nav_planner::systemControl >::value();
  }
  static const char* value(const ::nav_planner::systemControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAV_PLANNER_MESSAGE_SYSTEMCONTROL_H
