# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from nav_planner/gridRow.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import nav_planner.msg

class gridRow(genpy.Message):
  _md5sum = "b79fca104e1ff6a6b0cdcd662d07d607"
  _type = "nav_planner/gridRow"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """gridPoint[] row

================================================================================
MSG: nav_planner/gridPoint
int8 init
int8 proc"""
  __slots__ = ['row']
  _slot_types = ['nav_planner/gridPoint[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       row

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(gridRow, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.row is None:
        self.row = []
    else:
      self.row = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.row)
      buff.write(_struct_I.pack(length))
      for val1 in self.row:
        _x = val1
        buff.write(_get_struct_2b().pack(_x.init, _x.proc))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.row is None:
        self.row = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.row = []
      for i in range(0, length):
        val1 = nav_planner.msg.gridPoint()
        _x = val1
        start = end
        end += 2
        (_x.init, _x.proc,) = _get_struct_2b().unpack(str[start:end])
        self.row.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.row)
      buff.write(_struct_I.pack(length))
      for val1 in self.row:
        _x = val1
        buff.write(_get_struct_2b().pack(_x.init, _x.proc))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.row is None:
        self.row = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.row = []
      for i in range(0, length):
        val1 = nav_planner.msg.gridPoint()
        _x = val1
        start = end
        end += 2
        (_x.init, _x.proc,) = _get_struct_2b().unpack(str[start:end])
        self.row.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2b = None
def _get_struct_2b():
    global _struct_2b
    if _struct_2b is None:
        _struct_2b = struct.Struct("<2b")
    return _struct_2b
